[package]
name = "rust_calculation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.37.0"
plotters = "0.3.1"

# 時刻情報を扱うの利用（グラフ表示に必須ではない）
chrono = "0.4.19"